on:
  workflow_dispatch:
    inputs:
      env:
        description: "choose environment"
        required: true
        default: "staging"
        type: "choice"
        options:
          - staging
          - production
        
jobs:
  test-manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: choosen env
        run: echo "your env is ${{inputs.env}}"
